### ISSUE TITLE
Create Validations for Input field

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/vue-semantic#22]
Input field can have various validations.
- [ ] Date/Time Validation
- [ ] Range Validation
- [ ] Format Validation (Strinng/Number)
- [ ] Password Validation
- [ ] Email validation
- [ ] *Currency and other possible values.

Implement extensible and customization component which will expose these validations as api to user.

## Tasks:
- [ ] Source Code Implementation
- [ ] Unit Testcases
- [ ] Documentation
